version: "3"
services:
  app-mautic:
    build: .
    container_name: app-mautic
    ports:
    - "80:80"
    restart: unless-stopped
  app-mariadb:
    image: mariadb
    container_name: app-mariadb
    ports:
    - "3306:3306"
    environment: 
      MYSQL_DATABASE: mautic
      MYSQL_ROOT_PASSWORD: mautic@123
    restart: unless-stopped
